import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Bot, ChevronDown, ChevronUp, Pencil, Trash2, X, Check } from 'lucide-react'
import { Avatar, AvatarFallback, AvatarImage } from '@/client/components/ui/avatar'
import { Button } from '@/client/components/ui/button'
import { Textarea } from '@/client/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/client/components/ui/alert-dialog'
import { MarkdownContent } from '@/client/components/chat/MarkdownContent'
import { cn } from '@/client/lib/utils'
import { getErrorMessage } from '@/client/lib/api'
import { toast } from 'sonner'
import type { TicketComment } from '@/shared/types'

interface TicketCommentsListProps {
  comments: TicketComment[]
  isLoading: boolean
  currentUserId: string | null
  onUpdate: (commentId: string, content: string) => Promise<unknown>
  onDelete: (commentId: string) => Promise<unknown>
  /**
   * Maximum number of comments to render before showing a "show all" toggle.
   * When undefined, all comments are rendered. Most recent first (Jira-like).
   */
  maxVisible?: number
}

function authorInitials(name: string): string {
  const parts = name.trim().split(/\s+/).slice(0, 2)
  return parts.map((p) => p[0] ?? '').join('').toUpperCase() || '?'
}

function formatRelative(ms: number): string {
  const diff = Date.now() - ms
  if (diff < 60_000) return 'just now'
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`
  if (diff < 30 * 86_400_000) return `${Math.floor(diff / 86_400_000)}d ago`
  return new Date(ms).toLocaleDateString()
}

export function TicketCommentsList({
  comments,
  isLoading,
  currentUserId,
  onUpdate,
  onDelete,
  maxVisible,
}: TicketCommentsListProps) {
  const { t } = useTranslation()
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editingValue, setEditingValue] = useState('')
  const [pendingDeleteId, setPendingDeleteId] = useState<string | null>(null)
  const [savingId, setSavingId] = useState<string | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [expanded, setExpanded] = useState(false)

  // Sort newest first (Jira-like) without mutating the prop.
  const sortedComments = useMemo(
    () => [...comments].sort((a, b) => b.createdAt - a.createdAt),
    [comments],
  )

  const needsCollapse = typeof maxVisible === 'number' && sortedComments.length > maxVisible
  const visibleComments =
    needsCollapse && !expanded ? sortedComments.slice(0, maxVisible) : sortedComments
  const hiddenCount = sortedComments.length - visibleComments.length

  if (isLoading) {
    return (
      <p className="text-sm text-muted-foreground italic">
        {t('projects.ticket.comments.loading')}
      </p>
    )
  }

  if (comments.length === 0) {
    return (
      <p className="text-sm text-muted-foreground italic">
        {t('projects.ticket.comments.empty')}
      </p>
    )
  }

  function startEditing(comment: TicketComment) {
    setEditingId(comment.id)
    setEditingValue(comment.content)
  }

  function cancelEditing() {
    setEditingId(null)
    setEditingValue('')
  }

  async function saveEditing(commentId: string) {
    const trimmed = editingValue.trim()
    if (!trimmed) return
    setSavingId(commentId)
    try {
      await onUpdate(commentId, trimmed)
      cancelEditing()
    } catch (err) {
      toast.error(getErrorMessage(err))
    } finally {
      setSavingId(null)
    }
  }

  async function confirmDelete() {
    if (!pendingDeleteId) return
    setDeleting(true)
    try {
      await onDelete(pendingDeleteId)
      setPendingDeleteId(null)
    } catch (err) {
      toast.error(getErrorMessage(err))
    } finally {
      setDeleting(false)
    }
  }

  return (
    <>
      <ul className="space-y-4">
        {visibleComments.map((comment) => {
          const isKin = comment.author.type === 'kin'
          const canMutate = currentUserId !== null // any user can edit/delete per platform conventions
          const isEditing = editingId === comment.id
          const isAuto = !!comment.metadata?.autoGenerated
          const wasEdited = comment.updatedAt > comment.createdAt + 1000

          return (
            <li
              key={comment.id}
              className={cn(
                'flex gap-3 rounded-lg border border-border/60 p-3',
                isKin ? 'bg-muted/30' : 'bg-background',
              )}
            >
              <Avatar
                className={cn(
                  'size-8 shrink-0 ring-1',
                  isKin ? 'ring-primary/40' : 'ring-border',
                )}
              >
                {comment.author.avatarUrl && (
                  <AvatarImage src={comment.author.avatarUrl} alt={comment.author.name} />
                )}
                <AvatarFallback className="text-[10px] bg-secondary">
                  {authorInitials(comment.author.name)}
                </AvatarFallback>
              </Avatar>

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap text-sm">
                  <span className="font-medium">{comment.author.name}</span>
                  {isKin && (
                    <span className="rounded-full bg-primary/10 text-primary px-1.5 py-0.5 text-[10px] uppercase tracking-wide">
                      {t('projects.ticket.comments.kinTag')}
                    </span>
                  )}
                  {isAuto && (
                    <span
                      title={t('projects.ticket.comments.autoTooltip')}
                      className="flex items-center gap-1 rounded-full bg-muted text-muted-foreground px-1.5 py-0.5 text-[10px]"
                    >
                      <Bot className="size-3" />
                      {t('projects.ticket.comments.auto')}
                    </span>
                  )}
                  <span className="text-xs text-muted-foreground">
                    {formatRelative(comment.createdAt)}
                    {wasEdited && (
                      <span className="ml-1 italic">
                        ({t('projects.ticket.comments.edited')})
                      </span>
                    )}
                  </span>

                  {canMutate && !isEditing && (
                    <div className="ml-auto flex items-center gap-1">
                      <Button
                        size="icon"
                        variant="ghost"
                        className="size-6"
                        onClick={() => startEditing(comment)}
                        aria-label={t('projects.ticket.comments.edit')}
                      >
                        <Pencil className="size-3.5" />
                      </Button>
                      <Button
                        size="icon"
                        variant="ghost"
                        className="size-6 text-destructive hover:text-destructive"
                        onClick={() => setPendingDeleteId(comment.id)}
                        aria-label={t('projects.ticket.comments.delete')}
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </div>
                  )}
                </div>

                <div className="mt-2 text-sm">
                  {isEditing ? (
                    <div className="space-y-2">
                      <Textarea
                        value={editingValue}
                        onChange={(e) => setEditingValue(e.target.value)}
                        rows={3}
                        disabled={savingId === comment.id}
                      />
                      <div className="flex justify-end gap-2">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={cancelEditing}
                          disabled={savingId === comment.id}
                        >
                          <X className="mr-1 size-3.5" />
                          {t('projects.ticket.comments.cancel')}
                        </Button>
                        <Button
                          size="sm"
                          onClick={() => saveEditing(comment.id)}
                          disabled={
                            savingId === comment.id ||
                            editingValue.trim().length === 0 ||
                            editingValue.trim() === comment.content.trim()
                          }
                        >
                          <Check className="mr-1 size-3.5" />
                          {t('projects.ticket.comments.save')}
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <MarkdownContent content={comment.content} />
                  )}
                </div>
              </div>
            </li>
          )
        })}
      </ul>

      {needsCollapse && (
        <div className="mt-2 flex justify-center">
          <Button
            variant="ghost"
            size="sm"
            className="h-7 gap-1 px-2 text-xs text-muted-foreground hover:text-foreground"
            onClick={() => setExpanded((v) => !v)}
          >
            {expanded ? (
              <>
                <ChevronUp className="size-3" />
                {t('projects.ticket.comments.showLess')}
              </>
            ) : (
              <>
                <ChevronDown className="size-3" />
                {t('projects.ticket.comments.showMore', { count: hiddenCount })}
              </>
            )}
          </Button>
        </div>
      )}

      <AlertDialog open={pendingDeleteId !== null} onOpenChange={(open) => !open && setPendingDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('projects.ticket.comments.deleteConfirm.title')}</AlertDialogTitle>
            <AlertDialogDescription>
              {t('projects.ticket.comments.deleteConfirm.description')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleting}>
              {t('projects.ticket.comments.cancel')}
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDelete}
              disabled={deleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {t('projects.ticket.comments.deleteConfirm.confirm')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
